### PR TITLE
Update btagScaleFactor class

### PR DESCRIPTION
**Pull request by irenedutta23**
-  Update usage to new bTagScaleFactor class
-  Switch to V5 .csv file for 2017

Plots will be added soon

### CODE REVIEW

**Comment by jpata** [comment]
Make sure you commit also the updated version of the coffea submodule 🙂

```bash
cd hepaccelerate-cms/coffea
git branch #ensure you are on the latest version of coffea
cd .. #go to base repo
git commit coffea -m "update coffea version"
```

The commit should look something like the following, showing that the hash corresponding to the version has changed.
```bash
bash-4.2$ git diff coffea
diff --git a/coffea b/coffea
index 22e9519..9367728 160000
--- a/coffea
+++ b/coffea
@@ -1 +1 @@
-Subproject commit 22e95197d170f99e9336266c3895142d12432428
+Subproject commit 9367728689073b53bf0e260c95353f1370990336
```

**Comment by irenedutta23** [comment]
@jpata thanks for the suggestion. Do you know why the `import pandas` fails in the build?

**Comment by jpata** [comment]
hmm, it must be that coffea is now using pandas, which does not get installed in the test environment since we install coffea manually as part of our repository rather than using `pip install`. I think the solution would be to add `pip install coffea` here: https://github.com/jpata/hepaccelerate-cms/blob/master/.travis.yml#L27.

**Comment by irenedutta23** [comment]
Plots are here:
https://cernbox.cern.ch/index.php/s/cMFmskkRjoMvyrG

I see no difference in the light/ bc Flav plots compared to the previous versions

**Comment by nanlu06** [comment]
Thank you, Irene! look very good to me too.

**Pull request merged**
