### PR TITLE
sync angles and soft HT

### PR DESCRIPTION
**Pull request by nanlu06**
sync angles and (only CPU part) for soft jet variables

### CODE REVIEW

**Comment by nanlu06** [comment]
/storage/user/nlu/hmm/July12_pr118_validation

**Comment by nanlu06** [comment]
Check event Event 2338901910 Run 276363

HTSoft2 | CS_theta | CS_phi: 

62.457916 | 0.270913 | 1.679288

perfect agreement with Pisa

**Comment by irenedutta23** [comment]
Hi Nan, thanks for these changes.  I was just checking /storage/user/nlu/hmm/July12_pr118_validation/baseline/datacards/*
I see that the datacards are not renamed with *_era.root
Also, I don't see the nuisance changes I made in PR117
Can you please check this?

**Comment by nanlu06** [comment]
Thanks Irene. Datacard updated.

**Pull request merged**
