### PR TITLE
simplify how corrections are passed to the analysis

### PR DESCRIPTION
**Pull request by jpata**
Refactor and simplify the code, in particular how the various analysis corrections are passed through the code. We can just pass everything in the `analysis_corrections` object. No physics changes.

### CODE REVIEW

**Comment by jpata** [comment]
Validation plots: https://jpata.web.cern.ch/jpata/hmm/results/64ec4abe982fc0b2a047a9ca957e39a6c2e944bc/baseline/plots/

* 2016


* 2017


* 2018

**Comment by nanlu06** [comment]
Hi Joosep! Thank you very much. Since you have made the validation plots, I was just wondering if you happen to have the data card before and after this PR too?

**Comment by jpata** [comment]
The datacards with this PR included are available at https://jpata.web.cern.ch/jpata/hmm/results/64ec4abe982fc0b2a047a9ca957e39a6c2e944bc/baseline/. Note that this is with NanoAODv5 - the default in the code right now.

**Comment by nanlu06** [comment]
Thank you, Joosep! Good to merge from my side.

**Pull request merged**
