### PR TITLE
August week 4

### PR DESCRIPTION
**Pull request by jpata**
- new DNN model DNN27vars_sig_vbf_ggh_bkg_dyvbf_dy105To160_ewk105To160_split_60_40_mod10_190821
- errors for lepton SF
- LHE scale weights
- NNLOPS reweighting (partially done)
- scripts to run on Caltech HPC

### CODE REVIEW

**Comment by jpata** [comment]
Something to note before this PR is finalized, the memory usage has gone up, such that some jobs abort on Tier2 with `RequestMemory = 4000`. I'm testing to make sure we can still run the code.
cc @nanlu06

**Comment by nanlu06** [comment]
Thank you for testing this! I wonder, is this the physics analysis step and is it due to the LHEScaleweight?

**Comment by jpata** [comment]
Yes, it is the physics analysis step. Increasing `RequestMemory = 6000` allowed all jobs to run. Just keeping in mind that our servers have 125 GB / 48 cores, so this will currently leave 8 cores out of 48 unused on a server: `mem: 20*6GB = 120GB, cores: 48 - 20*2 = 8`.

Now all jobs completed and the output is in `/storage/user/jpata/hmm/forIrene/2019_09_05`. We can merge this PR and open a new development branch for future updates.

**Comment by nanlu06** [comment]
Great! Thank you. Yeah, opening a new development branch would be nice.

**Pull request merged**
