### PR TITLE
Add FSR recovery

### PR DESCRIPTION
**Pull request by kondratyevd**
Hi,

I've started implementing FSR recovery basing on the structure of private nanoAOD produced by Pisa group [0]. In this implementation, variables [Muon_pt_FSR, Muon_eta_FSR, Muon_phi_FSR] form a four-vector (with zero mass) that has to be added to the four-vector of a muon.

This PR is not ready for merging, as I haven't tested it yet and some parts are implemented quite naively (hmumu_utils.py L1412-1426), but you are welcome to review it and make suggestions while I continue working on it.

[0] [https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=%2F*%2Farizzi*FSR*V2*%2FUSER](https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fphys03&input=%2F*%2Farizzi*FSR*V2*%2FUSER)

### CODE REVIEW

**Comment by kondratyevd** [comment]
Hi, 

FSR recovery now seems to work. It can be turned on by adding `--do-fsr` option when running `analysis_hmm.py`.

I have tested it using this ggH file from privately produced nanoAOD by Pisa group:

root://t2-xrdcms.lnl.infn.it:7070///store/user/arizzi/nanoFSRV2/GluGlu_HToMuMu_M125_13TeV_powheg_pythia8/RunIISummer16MiniAODv3_nanoFSRV2_un2_asymptotic_v3-v2/190930_203831/0000/myNanoProdMc2016_NANO_1.root

 
Here is the mass spectrum before and after FSR recovery for that file:
[https://www.dropbox.com/s/0qv8naddg5jrupy/fsr_test.png?dl=0](https://www.dropbox.com/s/0qv8naddg5jrupy/fsr_test.png?dl=0)

**Comment by jpata** [comment]
Thanks Dmitry! Code-wise the changes look good to me.

I understand that there has been an effort by @nanlu06 and Andrea Rizzi to produce NanoAODs with the FSR photons included, and that soon there will be a NanoAOD V6 official production with those changes in. Apologies for being out of the loop a bit - can you help me understand if this PR is needed with the new Nano samples or if this is an alternative implementation? @nanlu06 do you know?

Thanks!

**Comment by kondratyevd** [comment]
Hi @jpata,

this implementation (latest commit) is for the private nanoAODs that are being produced by Caltech and Pisa groups right now. I didn't see the code for the new nanoAOD however, so this implementation relies on the fact that I interpreted the contents of the new branches correctly:

I assume that for every muon the branch `Muon_fsrPhotonIdx` contains the index of FSR photon associated with the muon from `FsrPhoton` collection for that event, or `-1` if no photons are associated with the muon. 

There should be no more than one FSR photon per muon, so `Muon_fsrPhotonIdx` is always 1-dimensional.

**Comment by nanlu06** [comment]
Hi Dmitry! Thank you a lot for implementing this for nanoAOD v6. I have reviewed it and it looks very good to me.

**Comment by nanlu06** [comment]
Hi Joosep! Just to confirm, this PR is needed with the new Nano samples v6.

**Pull request merged**
