### PR TITLE
Pdf weights

### PR DESCRIPTION
**Pull request by irenedutta23**
- Add pdf weights for all signal processes, dy and ewk
- Add pdf variation plots
- De-correlate QCD scale weights in Z peak and sidebands
- Add new binning for Pisa DNN plots

### CODE REVIEW

**Comment by jpata** [comment]
Thanks Irene! Can you check the automatic test [here](https://travis-ci.com/jpata/hepaccelerate-cms/builds/151216058). I think there is a bug:
```python
  File "/home/travis/build/jpata/hepaccelerate-cms/tests/hmm/hmumu_utils.py", line 696, in fill_histograms_several
    max_bins = max([b.shape[0] for b in all_bins])
  File "/home/travis/build/jpata/hepaccelerate-cms/tests/hmm/hmumu_utils.py", line 696, in <listcomp>
    max_bins = max([b.shape[0] for b in all_bins])
AttributeError: 'dict' object has no attribute 'shape'
```

**Comment by irenedutta23** [comment]
The plots and datacards are here:
https://cernbox.cern.ch/index.php/s/PdMOVLiR274euD2

To check the up/down variation on the Pisa DNN, please look at folders ending with the name `dnnPisa_pred2_*` (per model). I forgot to change the binning for the combined version i.e. `dnnPisa_pred2` (Will update next time)

The plots of the Pdf Weight up/ down variations look ok to me. I'm still checking the sensitivity numbers a little bit. With the default binning which is provided by Pisa, for the 3 region fit, I see a significance of around 1.0 for both prefit and postfit. For the 2 region fit, I see a significance of around 0.83, which is a bit suspicious.

**Comment by irenedutta23** [comment]
The plots and datacards are updated :
https://cernbox.cern.ch/index.php/s/PdMOVLiR274euD2
 With the default binning which is provided by Pisa, for the 3 region fit, I see a significance of around 1.07 for both prefit and postfit. For the 2 region fit, I see similar values.

**Comment by irenedutta23** [comment]
The plots and datacards for 2017 are updated :
https://cernbox.cern.ch/index.php/s/PdMOVLiR274euD2

I'm using equation 20 of https://arxiv.org/pdf/1510.03865.pdf for 2017 and 2018 to calculate the norm uncertainty . It's a bit large for vbf and tth, for eg vbf is 8% and tth is 6% in SR for 2017

**Pull request merged**
