### PR TITLE
refactor lorentz vector computations, cleanup updates

### PR DESCRIPTION
**Pull request by jpata**
Hey all, here is a set of bigger updates along with validation. Sorry that this comes in a big batch, rather than as smaller factorized updates. This was necessary, as I discovered a few issues from the last mmap->root update, and it seemed most efficient to just fix all the things together.

- improve submission scripts for the skim and analyze steps: submission is now done through `batch/make_cache_jdl.sh` and `batch/make_submit_jdl.sh`, both preparing a list of arguments for a single submission script (cache.jdl or analyze.jdl respectively).
- make sure integrated luminosity is computed with the `LuminosityBlocks` TTree from NanoAOD, mitigating any effects from skimming if a luminosity block would be completely dropped by the skim
- significantly improve memory performance of the code when running CPU-only by loading only chunks of a file at a time (update to the main kernel library [hepaccelerate](https://github.com/hepaccelerate/hepaccelerate)), such that we use definitely under 2GB/core of memory, fitting nicely with existing machines.
- Put all the Lorentz vector conversions in the base [hepaccelerate](https://github.com/hepaccelerate/hepaccelerate) library.
- make sure the GPU version is working when `HEPACCELERATE_CUDA=1` is specified (further GPU optimizations still need to be carried out)
- remove some duplicated datasets in `data/datasets_NanoAODv5.yml` which can cause issues with the skim jobs
- disable PUID weight, as it seems to mess up the prediction at least in 2018, needs to be validated for all years independently
- improve tests, add a test for the full `run_analysis` functionality that includes file splitting
- update singularity image with intel python distribution & optimized tensorflow
- clean notebook outputs

Will need to do
```
git submodule sync
git submodule update
```

### CODE REVIEW

**Comment by kondratyevd** [comment]
Hi @jpata, will this implementation work with usual non-columnar variables (for example to sum one muon and one fsr photon inside the numba loop) or only with columnar objects?

**Comment by jpata** [comment]
The CPU version works with either transparently. The GPU version will have one for the big arrays and one to call on just individual values.

**Comment by jpata** [comment]
Validation jobs are almost done, aiming to merge this tomorrow.

**Comment by jpata** [comment]
Validation plots for fast mode (no tensorflow, total JEC) are [here](http://jpata.web.cern.ch/jpata/hmm/results/610628db19d732900432e6651e514e4bf52ed89d).

Validation plots for the full mode (DNNs enabled, factorized JEC): *pending*

**Comment by jpata** [comment]
~3.5x speedup with 0c36cac, changing batch size in Pisa DNN prediction:
- number of jobs: 355
- runtime = 1944.28 +- 985.80 s
- maxrss = 2497.78 +- 150.91 MB
- speeds = 1564.19 +- 688.10 Hz

**Pull request merged**
